### ISSUE TITLE
Problem with parsing JSON file

### ISSUE THREAD

**Issue by JaikrishnaTS** [ipop-project/controllers#70]
I use a JSON tool (jq) for automatically modifying the configuration files of IPOP. 
The tool, for some reason reorders the fields in the configuration JSON file, but the result is exactly same as modifying by hand. 

I had been using the tool for some weeks now and suddenly today the controller ran into an error on one of the JSON files. 

The error log reads:
`CFx initialized. Loading Controller Modules

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/grapleadmin/ipopbin/controller/Controller.py", line 13, in <module>
    main()
  File "/home/grapleadmin/ipopbin/controller/Controller.py", line 8, in main
    CFx.initialize()
  File "controller/framework/CFx.py", line 138, in initialize
    self.load_module(key)
  File "controller/framework/CFx.py", line 195, in load_module
    handle.initialize()
  File "controller/framework/CFxHandle.py", line 45, in initialize
    self.CMInstance.initialize()
  File "controller/modules/StatReport.py", line 27, in initialize
    self.CFxHandle.submitCBT(logCBT)
  File "controller/framework/CFxHandle.py", line 28, in submitCBT
    self.__CFxObject.submitCBT(cbt)
  File "controller/framework/CFx.py", line 60, in submitCBT
    self.CFxHandleDict[recipient].CMQueue.put(CBT)
KeyError: 'Logger'
`

EDIT: Also used an online comparison tool and it says the configurations are same. (http://tlrobinson.net/projects/javascript-fun/jsondiff)

Attached JSON files for reference. Appended to .txt for Github support.

[notworking-gvpn-config.json.txt](https://github.com/ipop-project/controllers/files/201055/notworking-gvpn-config.json.txt)
[working-gvpn-config.json.txt](https://github.com/ipop-project/controllers/files/201054/working-gvpn-config.json.txt)

**Comment by JaikrishnaTS** [comment]
Looks like it was solved by #68
