### ISSUE TITLE
psutil Error

### ISSUE THREAD

**Issue by vahid-dan** [ipop-project/Controllers#78]
For `ipop-vpn_lnx-beta1r05` running the controller on my Ubuntu 14.04.5 laptop throws an error:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vd/ipop-vpn_lnx-beta1r05/controller/Controller.py", line 32, in <module>
    main()
  File "/home/vd/ipop-vpn_lnx-beta1r05/controller/Controller.py", line 21, in main
    while checkTincanState() == False:
  File "/home/vd/ipop-vpn_lnx-beta1r05/controller/Controller.py", line 12, in checkTincanState
    if process.name().find("tincan")!=-1 or process.name() == "ipop-tincan":
TypeError: 'str' object is not callable
```
A quick fix for that would be:
In `Controller.py` lines 5-14:
```
# Function checks the system process table for Tincan process
def checkTincanState():
    for process in psutil.process_iter():
-       if type(process) is str:
-           if process.find("tincan")!=-1 or process == "ipop-tincan":
-               return True
-       else:
-           if process.name().find("tincan")!=-1 or process.name() == "ipop-tincan":
-               return True
    return False
```
```
# Function checks the system process table for Tincan process
def checkTincanState():
    for process in psutil.process_iter():
+       if str(process).find("tincan")!=-1 or process == "ipop-tincan":
+           return True
    return False
```
It was working fine right out of the box on a VM on the same laptop and also on my other machine with exactly the same operating system.

Vahid

**Comment by vdaneshmand** [comment]
The problem is most probably because of `psutil` version. The `psutil` on my laptop is `1.2.1` but on the other machine is `5.2.0`. As far as I know, I installed both of them the same way.
